const CHARACTERS_LOADED = "CHARACTERS_LOADED";
const CHARACTERS_SELECTED = "CHARACTERS_SELECTED";
const SET_TAGS = "SET_TAGS";
const SEARCH_TEXT_UPDATE = "SEARCH_TEXT_UPDATE";
const TAGS_SELECTED = "TAGS_SELECTED";

const TAG_MY_TEAM = "my team";
const MAX_TEAM_MEMBERS = 6;

export {
  CHARACTERS_LOADED,
  CHARACTERS_SELECTED,
  MAX_TEAM_MEMBERS,
  SEARCH_TEXT_UPDATE,
  SET_TAGS,
  TAG_MY_TEAM,
  TAGS_SELECTED,
};
